sequential = false
pipeline_placement = "start"
max_pipeline_length = 80
skip_external_parse_errors = true
explicit_optional_access = false

[groups]

[rules]
redundant_nu_subprocess = "off"
nu_parse_error = "off"
unused_helper_functions = "off"
spread_list_to_external = "off"
