sequential = false
pipeline_placement = "start"
max_pipeline_length = 80
skip_external_parse_errors = true
explicit_optional_access = false

[groups]

[rules]
unused_helper_functions = "off"
redundant_nu_subprocess = "off"
